#! /bin/sh

exec sxhkd &
xrandr -s 1920x1080 &
nitrogen --restore &
picom &
xsetroot -cursor_name left_ptr &
pkill polybar && sleep 1 
polybar -c ~/.config/polybar/config.ini &

# firefox

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          10

bspc config normal_border_color "#4c566a"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#d8dee9"
bspc config presel_feedback_color "#2e3440"

bspc config split_ratio          0.5

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config borderless_monocle   true
bspc config gapless_monocle      true
